<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<meta http-equiv="x-ua-compatible" content="ie=edge" />';
echo '<title>Footer</title>';
echo '<link rel="stylesheet" type="text/css" href="../About_us/style.css">';
echo '<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->';
echo '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />';
echo '</head>';
echo '';
echo '<body class="para" style="color: white">';
echo '<footer style="background-color: black">';
echo '<div class="box">';
echo '<div class="litle_box" class="col-lg-4 col-md-6 mb-4 mb-md-0">';
echo '<h3 class="underline">';
echo 'MIRACLE MOTORS';
echo '</h3>';
echo '<span>We sell wide range of vehicles such as classic vehicles to the latest brand new vehicles.
            We merged with several leasing companies and facilitate customer to get leasing easily. </span>';
echo '</div>';
echo '';
echo '<div class="litle_box">';
echo '<h3 class="underline">';
echo 'INFORMATION';
echo '</h3>';
echo '<ul style="list-style: none;">';
echo '<span class="space">';
echo '<a href="http://localhost/Miracle-Loop/homepage/home.php" style="color:white;">HOME</a>';
echo '</span></br>';
echo '<span class="space">';
echo '<a href="http://localhost/Miracle-Loop/About_us/Aboutus.php" style="color:white;">ABOUT US</a>';
echo '</span></br>';
echo '<span class="space">';
echo '<a href="#!" style="color:white;">VEHICLES</a>';
echo '</span></br>';
echo '<span class="space">';
echo '<a href="#!" style="color:white;">CONTACT US</a>';
echo '</span>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="litle_box">';
echo '<h3 class="underline">';
echo 'OUR LEASING PARTNER';
echo '</h3>';
echo '<span class="space"> PEOPLES LEASING </span></br>';
echo '<span class="space"> COMMERCIAL LEASING </span></br>';
echo '<span class="space"> SEYLAN LEASING </span>';
echo '</div>';
echo '';
echo '<div class="litle_box">';
echo '<h3 class="underline">';
echo 'CONTACT DETAILS';
echo '</h3>';
echo '<span class="space">';
echo '<i class="fas fa-phone mr-3"></i> 011 3456788';
echo '</span></br>';
echo '<span class="space">';
echo '<i class="fas fa-print mr-3"></i> 011 3456789';
echo '</span></br>';
echo '<span class="space">';
echo '<i class="fas fa-envelope mr-3"></i> info@gmail.com';
echo '</span></br>';
echo '<span class="space">';
echo '<i class="fas fa-home mr-3"></i>No/51, Nidhas Mawatha, Colombo 07';
echo '</span>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<hr class="mb-4" />';
echo '</br>';
echo '<!-- Section: Social media -->';
echo '<div>';
echo '<!-- Facebook -->';
echo '<a class="fa" href="www.facebook.com" role="button">';
echo '<i class="fab fa-facebook"></i>';
echo '</a>';
echo '<!-- Twitter -->';
echo '<a class="fa" href="www.twitter.com" role="button">';
echo '<i class="fab fa-twitter"></i>';
echo '</a>';
echo '<!-- Google -->';
echo '<a class="fa" href="https://www.google.com/" role="button">';
echo '<i class="fab fa-google"></i>';
echo '</a>';
echo '<!-- youtube -->';
echo '<a class="fa" href="www.youtube.com" role="button">';
echo '<i class="fab fa-youtube"></i>';
echo '</a>';
echo '<!-- Instagram -->';
echo '<a class="fa" href="www.instagram.com" role="button">';
echo '<i class="fab fa-instagram"></i>';
echo '</a>';
echo '</div>';
echo '</br>';
echo '<!--</div>-->';
echo '<!-- Grid container -->';
echo '<!-- Copyright -->';
echo '<!--<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">';
echo '';
echo '© 2020 Copyright:';
echo '<a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a></div>-->';
echo '</footer>';
echo '</body>';
echo '</html>';
echo '';
?>